trigger:
- main
- prod

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
    architecture: 'x64'

- script: |
    echo Installing requirements...
    pip install .

- script: |
    pytest

  displayName: 'Run tests'
